### ISSUE TITLE
Error:Cannot change dependencies of configuration ':flip-concept:_debugAnnotationProcessor' after it has been resolved.

### ISSUE THREAD

**Issue by Xy-joe** [vpaliyX/LoginConcept#4]
I don't really know the dependency that's causing this error after i cloned this repository and tried running this app

**Comment by vpaliy** [comment]
Looks like you are trying to run the `flip-concept` module. Just change it to the `app` module and that's it.

**Comment by Xy-joe** [comment]
That's was quite helpful. I did just that and it worked perfectly

**Comment by vpaliy** [comment]
Yep. The `flip-concept` is just another example which I haven't finished yet.

**Comment by Xy-joe** [comment]
I don't know could you give me a facebook link to chat you up with.

**Comment by vpaliy** [comment]
I don't own a Facebook account, but you can send an email (vpaliy97@gmail.com). Or a message on my Tweeter ![vpaliy_](https://twitter.com/vpaliy_).

**Comment by Xy-joe** [comment]
How do you perform an action on the Vertical textView in both the sign in fragment and the login fragment because i don't really know the method to set the OnClickListener for the "Login" and "Sign up". 
Say for example you wanted to really sign Up or Login

**Comment by vpaliy** [comment]
You need to write the implementation yourself. Just simply add a listener, and write the Sign Up/Login implementation. This example is just an animation stuff.
